version: "3"

services:
  web:
    image: paris/ceryx-web:latest
    environment:
      CERYX_API_HOST: ${CERYX_API_HOST}
    networks:
      default:
      ceryx:
        aliases:
          - ceryx.${CERYX_WEB_NAME:-web}
networks:
  ceryx:
    external: true
